const navigationStrings = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  FORGOT_SCREEN:'FORGOT_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  SHOP_SCREEN: 'SHOP_SCREEN',
  VIDEO_SCREEN: 'VIDEO_SCREEN',
  CALENDER_SCREEN: 'CALENDER_SCREEN',
  MORE_SCREEN: 'MORE_SCREEN',
  PRODUCT_DETAILS_SCREEN: 'PRODUCT_DETAILS_SCREEN',
  CART_SCREEN:'CART_SCREEN',
  CarouselFullImagePinchable: 'CarouselFullImagePinchable',

  HOME_STACK: 'HOME_STACK',
  SHOP_STACK: 'SHOP_STACK',
  TAB_NAVIGATOR: 'TAB_NAVIGATOR',

};

export default navigationStrings;
